#!/usr/bin/env node
/* ============================================================
   AirCrew Jobs — verified-catalog → database sync generator
   Usage: node tools/sync-jobs.js   (also runs as part of generate-airlines.js)

   Reads the verified listings in assets/data.js and emits
   supabase/sync-jobs.sql — paste it into the Supabase SQL Editor
   after ANY change to the catalog. It is idempotent:
   - upserts every verified listing under its stable data.js id
   - removes verified rows that are no longer in the catalog
   - never touches recruiter posts (verified = false)
   ============================================================ */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const src = fs.readFileSync(path.join(ROOT, "assets", "data.js"), "utf8");
const ctx = {};
new Function("ctx", src.replace(/^const /gm, "ctx.") + ";")(ctx);
const { JOBS } = ctx;

const q = s => "'" + String(s ?? "").replace(/'/g, "''") + "'";
const verified = JOBS.filter(j => j.verified);

const rows = verified.map(j => `(${j.id}, ${q(j.airline)}, ${q(j.role)}, ${q(j.aircraft)}, ${q(j.region)}, ${q(j.location)}, ${q(j.type)}, ${j.minHours || 0}, ${j.rated ? "true" : "false"}, ${q(j.salary)}, true, ${q(j.applyUrl)}, ${j.reqs ? q(j.reqs) : "null"}, ${q(j.category || "pilot")}, ${j.added ? q(j.added) + "::timestamptz" : "now()"})`).join(",\n");

const ids = verified.map(j => j.id).join(", ");

const sql = `-- ============================================================
-- AUTO-GENERATED by tools/sync-jobs.js — ${new Date().toISOString().slice(0, 10)}
-- Syncs the verified catalog (assets/data.js) into the live DB.
-- Idempotent: run it after every catalog change. Recruiter posts
-- (verified = false) are never touched.
-- ============================================================
begin;

insert into public.jobs
  (id, airline, role, aircraft, region, location, type, min_hours, rated, salary, verified, apply_url, reqs, category, posted_at)
overriding system value
values
${rows}
on conflict (id) do update set
  airline = excluded.airline, role = excluded.role, aircraft = excluded.aircraft,
  region = excluded.region, location = excluded.location, type = excluded.type,
  min_hours = excluded.min_hours, rated = excluded.rated, salary = excluded.salary,
  verified = true, apply_url = excluded.apply_url, reqs = excluded.reqs,
  category = excluded.category, posted_at = excluded.posted_at;

-- remove verified listings that left the catalog (closed/withdrawn)
delete from public.jobs where verified = true and id not in (${ids});

-- keep the identity sequence clear of catalog ids (recruiter posts get ids >= 1000)
select setval(pg_get_serial_sequence('public.jobs', 'id'),
  greatest((select coalesce(max(id), 0) + 1 from public.jobs), 1000), false);

commit;

-- sanity check: should match data.js (${verified.length} verified listings)
select count(*) filter (where verified) as verified_jobs,
       count(*) filter (where not verified) as recruiter_posts
from public.jobs;
`;

fs.writeFileSync(path.join(ROOT, "supabase", "sync-jobs.sql"), sql);
console.log(`✓ supabase/sync-jobs.sql — ${verified.length} verified listings`);
